# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo_inference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo_inference.proto',
  package='demo_inference',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x64\x65mo_inference.proto\x12\x0e\x64\x65mo_inference\"\x1d\n\x0bObservation\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06values\x18\x01 \x03(\x02\x62\x06proto3')
)




_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='demo_inference.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='demo_inference.Observation.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=69,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='demo_inference.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='demo_inference.Action.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVATION,
  __module__ = 'demo_inference_pb2'
  # @@protoc_insertion_point(class_scope:demo_inference.Observation)
  ))
_sym_db.RegisterMessage(Observation)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'demo_inference_pb2'
  # @@protoc_insertion_point(class_scope:demo_inference.Action)
  ))
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
