# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/franka.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/franka.proto',
  package='franka',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12proto/franka.proto\x12\x06\x66ranka\"@\n\nJointState\x12\x10\n\x08position\x18\x01 \x01(\x01\x12\x10\n\x08velocity\x18\x02 \x01(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x03 \x01(\x01\"B\n\x0cJointCommand\x12\x10\n\x08position\x18\x01 \x01(\x01\x12\x10\n\x08velocity\x18\x02 \x01(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x03 \x01(\x01\"5\n\x0fJointStateArray\x12\"\n\x06states\x18\x01 \x03(\x0b\x32\x12.franka.JointState\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"7\n\tQuatenion\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"B\n\x04Pose\x12\x1a\n\x03pos\x18\x01 \x01(\x0b\x32\r.franka.Point\x12\x1e\n\x03rot\x18\x02 \x01(\x0b\x32\x11.franka.Quatenion\"\xe1\x01\n\x0cRobotCommand\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.franka.RobotCommand.Type\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x0c\n\x04note\x18\x04 \x01(\t\x12$\n\x06joints\x18\x05 \x03(\x0b\x32\x14.franka.JointCommand\x12\x10\n\x08sys_time\x18\x06 \x01(\x02\"B\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n\tTYPE_DEMO\x10\x01\x12\x15\n\x11TYPE_JOINT_TARGET\x10\x02\"\xe9\x01\n\x10RobotObservation\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.franka.RobotObservation.Type\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x0c\n\x04note\x18\x04 \x01(\t\x12$\n\x06joints\x18\x05 \x03(\x0b\x32\x14.franka.JointCommand\x12\x10\n\x08sys_time\x18\x06 \x01(\x02\"B\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n\tTYPE_DEMO\x10\x01\x12\x15\n\x11TYPE_JOINT_TARGET\x10\x02\";\n\x0bStampedPose\x12\x1a\n\x04pose\x18\x01 \x01(\x0b\x32\x0c.franka.Pose\x12\x10\n\x08sys_time\x18\x02 \x01(\x02\x62\x06proto3')
)



_ROBOTCOMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='franka.RobotCommand.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_DEMO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_JOINT_TARGET', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=546,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_ROBOTCOMMAND_TYPE)

_ROBOTOBSERVATION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='franka.RobotObservation.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_DEMO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_JOINT_TARGET', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=546,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_ROBOTOBSERVATION_TYPE)


_JOINTSTATE = _descriptor.Descriptor(
  name='JointState',
  full_name='franka.JointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='franka.JointState.position', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='franka.JointState.velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effort', full_name='franka.JointState.effort', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=94,
)


_JOINTCOMMAND = _descriptor.Descriptor(
  name='JointCommand',
  full_name='franka.JointCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='franka.JointCommand.position', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='franka.JointCommand.velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effort', full_name='franka.JointCommand.effort', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=162,
)


_JOINTSTATEARRAY = _descriptor.Descriptor(
  name='JointStateArray',
  full_name='franka.JointStateArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='states', full_name='franka.JointStateArray.states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=217,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='franka.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='franka.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='franka.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='franka.Point.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=259,
)


_QUATENION = _descriptor.Descriptor(
  name='Quatenion',
  full_name='franka.Quatenion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='franka.Quatenion.w', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='franka.Quatenion.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='franka.Quatenion.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='franka.Quatenion.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=316,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='franka.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='franka.Pose.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rot', full_name='franka.Pose.rot', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=384,
)


_ROBOTCOMMAND = _descriptor.Descriptor(
  name='RobotCommand',
  full_name='franka.RobotCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='franka.RobotCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='franka.RobotCommand.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='franka.RobotCommand.mode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='franka.RobotCommand.note', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joints', full_name='franka.RobotCommand.joints', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time', full_name='franka.RobotCommand.sys_time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTCOMMAND_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=612,
)


_ROBOTOBSERVATION = _descriptor.Descriptor(
  name='RobotObservation',
  full_name='franka.RobotObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='franka.RobotObservation.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='franka.RobotObservation.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='franka.RobotObservation.mode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='franka.RobotObservation.note', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joints', full_name='franka.RobotObservation.joints', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time', full_name='franka.RobotObservation.sys_time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTOBSERVATION_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=848,
)


_STAMPEDPOSE = _descriptor.Descriptor(
  name='StampedPose',
  full_name='franka.StampedPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='franka.StampedPose.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time', full_name='franka.StampedPose.sys_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=850,
  serialized_end=909,
)

_JOINTSTATEARRAY.fields_by_name['states'].message_type = _JOINTSTATE
_POSE.fields_by_name['pos'].message_type = _POINT
_POSE.fields_by_name['rot'].message_type = _QUATENION
_ROBOTCOMMAND.fields_by_name['type'].enum_type = _ROBOTCOMMAND_TYPE
_ROBOTCOMMAND.fields_by_name['joints'].message_type = _JOINTCOMMAND
_ROBOTCOMMAND_TYPE.containing_type = _ROBOTCOMMAND
_ROBOTOBSERVATION.fields_by_name['type'].enum_type = _ROBOTOBSERVATION_TYPE
_ROBOTOBSERVATION.fields_by_name['joints'].message_type = _JOINTCOMMAND
_ROBOTOBSERVATION_TYPE.containing_type = _ROBOTOBSERVATION
_STAMPEDPOSE.fields_by_name['pose'].message_type = _POSE
DESCRIPTOR.message_types_by_name['JointState'] = _JOINTSTATE
DESCRIPTOR.message_types_by_name['JointCommand'] = _JOINTCOMMAND
DESCRIPTOR.message_types_by_name['JointStateArray'] = _JOINTSTATEARRAY
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Quatenion'] = _QUATENION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['RobotCommand'] = _ROBOTCOMMAND
DESCRIPTOR.message_types_by_name['RobotObservation'] = _ROBOTOBSERVATION
DESCRIPTOR.message_types_by_name['StampedPose'] = _STAMPEDPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointState = _reflection.GeneratedProtocolMessageType('JointState', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATE,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.JointState)
  ))
_sym_db.RegisterMessage(JointState)

JointCommand = _reflection.GeneratedProtocolMessageType('JointCommand', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCOMMAND,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.JointCommand)
  ))
_sym_db.RegisterMessage(JointCommand)

JointStateArray = _reflection.GeneratedProtocolMessageType('JointStateArray', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATEARRAY,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.JointStateArray)
  ))
_sym_db.RegisterMessage(JointStateArray)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.Point)
  ))
_sym_db.RegisterMessage(Point)

Quatenion = _reflection.GeneratedProtocolMessageType('Quatenion', (_message.Message,), dict(
  DESCRIPTOR = _QUATENION,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.Quatenion)
  ))
_sym_db.RegisterMessage(Quatenion)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.Pose)
  ))
_sym_db.RegisterMessage(Pose)

RobotCommand = _reflection.GeneratedProtocolMessageType('RobotCommand', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTCOMMAND,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.RobotCommand)
  ))
_sym_db.RegisterMessage(RobotCommand)

RobotObservation = _reflection.GeneratedProtocolMessageType('RobotObservation', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTOBSERVATION,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.RobotObservation)
  ))
_sym_db.RegisterMessage(RobotObservation)

StampedPose = _reflection.GeneratedProtocolMessageType('StampedPose', (_message.Message,), dict(
  DESCRIPTOR = _STAMPEDPOSE,
  __module__ = 'proto.franka_pb2'
  # @@protoc_insertion_point(class_scope:franka.StampedPose)
  ))
_sym_db.RegisterMessage(StampedPose)


# @@protoc_insertion_point(module_scope)
